version: '3'

services:
  redis:
    image: redis
    hostname: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  app:
    depends_on:
      - db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000-3010:3000'
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - data_db:/var/lib/postgresql/data
volumes:
  data_db:
  redis_data:
